language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - "3.7-dev"
  - "nightly"
  allow_failures:
  - pypy3.5-5.7.1-beta

install:
  - pip install pycrypto
  - pip install pymongo

services: mongodb

before_script:
  - bash mongo_insert.sh

script:
  - python destest.py

