language: python
python:
  #- 3.3
  #- 3.4
  #- 3.5
  - 3.6
  #- "3.7-dev"
  #- "nightly"
  ##- pypy3.5-5.7.1-beta

install:
  - pip install pycrypto
  - pip install pymongo

services: mongodb

before_script:
  - mongo --eval 'db.counters.insert({"id": "user_id", seq: 0});'

script:
  - python destest.py

