language: python
python:
  #- 3.3
  #- 3.4
  #- 3.5
  - 3.6
  #- "3.7-dev"
  #- "nightly"
  ##- pypy3.5-5.7.1-beta

install:
  - pip install pymongo

services: mongodb

before_script:
  - python mongo_insert.py

script:
  - python destest.py
